lightning_module: 
  _target_: lightning_vocoders.models.hifigan.lightning_module.HiFiGANLightningModule

generator:
  upsample_rates: [8,8,4]
  upsample_initial_channel: 256
  upsample_kernel_sizes: [16,16,8]
  resblock_dilation_sizes: [[1,2], [2,6], [3,12]]
  resblock_kernel_sizes: [3,5,7]
  resblock: "2"

optim:
  opt_g:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8,0.99]
  opt_d:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8,0.99]
  scheduler_g:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.999
  scheduler_d:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.999
