trainer:
  _target_: lightning.Trainer
  accelerator: "gpu"
  devices: [0]
loggers:
  - _target_: lightning.pytorch.loggers.TensorBoardLogger
    save_dir: "tb_logs"
  # - _target_: lightning.pytorch.loggers.WandbLogger
  #   project: "hifigan-lightning"
